apiVersion: apps/v1
kind: Deployment
metadata:
   name:  platform-depl
spec:
   replicas: 1    
   selector:
      matchLabels:
        app: platformservice
   template:     
      metadata: 
        labels:
         app: platformservice
      spec:     
        containers:
           - name:  platfromservice
             image: 6895mahfuz/platformservice:latest

          
          